### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by gszasz** [michal-h21/iec2utf#3]
Since the project has [no license](http://choosealicense.com/no-license/), it defaults in the [copyright law](https://en.wikipedia.org/wiki/Copyright) plus [GitHub Term of Service](https://help.github.com/articles/github-terms-of-service/).  Under these circumstances my recent contributions to this repository were illegal, because I did not ask author for permission to modify his code prior the commits gszasz/iec2utf@e50a1e271eb2142fe777b741534776a0bec6266c and gszasz/iec2utf@3e45c8b2f7ec8eaeac001596513b3ec12cb12f3b.

This legal issue should be resolved by adding a specific LICENSE file to the repository. For instance, xindy itself uses GPLv2, thus GPL (either v2 or v3) would be natural choice for this wrapper.

**Comment by michal-h21** [comment]
Thank you for noticing this, I added the LICENSE.md file. Github now provides templates for most common licenses, with GPL v3 available, so I've selected it.

**Comment by gszasz** [comment]
Note that GitHub populated your `LICENSE.md` file with the [plain text GNU GPLv3](https://raw.githubusercontent.com/michal-h21/iec2utf/master/LICENSE.md) that wasn't formatted using Markdown syntax (although some elements are compatible with Markdown).  Due to the `.md` extension, GitHub tries to render plain text content of the `LICENSE.md` as Markdown document and [the result](https://github.com/michal-h21/iec2utf/blob/master/LICENSE.md) looks quite funny.  It seems that GitHub is not that smart, since it doesn't offer [Markdown formatted GNU GPL v3 license](https://www.gnu.org/licenses/gpl-3.0.md) when you name your license file `LICENSE.md`.

I'd recommend either to replace the content of the `LICENSE.md` file with the [Markdown formatted GNU GPL v3 license](https://www.gnu.org/licenses/gpl-3.0.md) or to keep current content and simply rename `LICENSE.md` to `LICENSE`.
